### ISSUE TITLE
Markdown shortcuts support?

### ISSUE THREAD

**Issue by ashutoshsaboo** [SebTota/TipTapSN#1]
Just came across this, fantastic editor! Would it be possible to add markdown shortcuts to this? I came across this, I'm not too sure if helps/if tiptap already supports it - https://tiptap.dev/examples/markdown-shortcuts ? The idea is something like to have a best-of-both worlds kinda editor - markdown shortcuts wherever possible for speed + html customizations which tiptap already offers for full customizability (to be clear: the rendering part can stay in html itself which tiptap already does)! On mobile as well, markdown support would help for tremendous speed, since the wysiwyg menu is at the top (saving loads of finger switching time)! 

Would you be willing to add something like this? @SebTota

**Comment by SebTota** [comment]
Hello,
This is already supported on the editor. Please see the video attached for an example and let me know if you are referring to something else instead. 

https://user-images.githubusercontent.com/25122511/146069951-1bf95ba1-1d81-4952-b3f0-3f8db0cfb891.mov

**Comment by SebTota** [comment]
I also want to add because I saw you commented on my other editor as well, I am not currently working on either editor. As I was working on this editor extension for Standard Notes I realized that I was essentially creating my own entire note app within the constraints of an existing application, especially when it came to the collaborative aspect of this editor.

While I love what the team at Standard Notes is doing, I've found it really difficult and annoying to work around the constraints of their application to create the exact editor that I needed for my use case. I find that Standard Notes is a great note taking application, but only for a VERY specific type of person. I may revisit Standard Notes and the editors that I've created at some point soon to see if anything has changed, but as of right now Standard Notes is just not what I was looking for so the development of this editor has stopped from my end.
